### ISSUE TITLE
3.0.1 -> 3.1.1 Change of behaviour

### ISSUE THREAD

**Issue by sunnyhighway** [jsreport/jsreport-dotnet-client#3]
In version 3.0.1 the following condition resulted in FALSE when **invoice** was NULL

`{{if invoice.paid}}`

In version 3.1.0 and 3.1.1 it results in the following exception:
`Error during rendering report: Error during rendering report: Cannot read property 'paid' of undefined`

**Comment by pofider** [comment]
Please share the full error. 
What is the version of the jsreport server?

**Comment by sunnyhighway** [comment]
We are running this lib against jsreport 1.0.9

The entire exception the jsreprt.client lib gives is stated above.
The exception contains no stack trace.

**Comment by pofider** [comment]
I see that jsreport 1.0.9 and the latest 2.11 both crashes in such case you describe.

See it here
https://playground.jsreport.net/w/anon/FlURSD97

jsrender behaves this way and we haven't changed this on our end.

**Comment by sunnyhighway** [comment]
The bug was on our end. The test data sent to jsreports was not 100% identical. This problem occurred because of a mix of typed classes vs dynamic classes causing the data to be serialised differently.
