### ISSUE TITLE
Use resources with the dotnetclient

### ISSUE THREAD

**Issue by engern** [jsreport/jsreport-dotnet-client#4]
Hi,

We use [Resources ](https://jsreport.net/learn/resources) with our JS Reports, and wish to use this dotnet client. How do I sepcify this  part of the request in the dotnet client: **"options": { "language": "en" }**

**Comment by pofider** [comment]
You can use [this](https://github.com/jsreport/jsreport-dotnet-shared/blob/master/jsreport.Shared/IRenderService.cs#L18) override.

```csharp
rs.RenderAsync(new RenderRequest {
  Template = new Templates {
    Name = "xxxx"
  },
  Data = new { ... },
  Options = new RenderOptions  { Language = "en" }
}
```
