### ISSUE TITLE
Problem with 3.2.0

### ISSUE THREAD

**Issue by NeilSorensen** [jsreport/jsreport-dotnet-client#9]
When we upgraded to 3.2.0 from 3.1.1, we started getting JsReportExceptions with the message "Unable to render template. Protocol error (Page.printToPDF): scale is outside [0.1 - 2] range"

We have not been explicitly setting the scale (and I don't see an obvious place to set it). Let me know if there's anything more we can provide to help figure out what's going wrong.

**Comment by pofider** [comment]
Sorry for the trouble. It should be fixed in 3.2.1 I've just published
